/******************************************************************************
 * File:        BranchSpawn.h
 * Project:     Branching Morphogenesis Simulator
 * Author:      Dr. Sabyasachi Sutradhar
 * Affiliation: Howard Lab, Yale University
 * Email:       sabyasachi.sutradhar@yale.edu
 *
 * Description:
   This header file generates new branches through spawning (side branching and bifurcation) new branches.
 * License:
 *   This software is developed for academic research purposes and is
 *   distributed under the MIT License (or specify another if applicable).
 *
 * Last Modified:    Dec 04, 2025
 *
 * Usage Notes:
 *   - Requires C++17 or later.
 *   - Dependencies: This codebase needs CMake, libtiff
 *
 * References:
 *   [1] Shree, Sutradhar, et al., Sci. Adv. 8, eabn0080 (2022) 29 June 2022
 *   [2] Ouyang, Sutradhar et al.  Nature Comm. 
 *
 ******************************************************************************/
#include <fstream>
#include <string>
#include <vector>
#include <sstream>
#include <iomanip>
#include <cmath>
#include <array>
#include "PrintTIFF.h"


inline bool Within_ImageTiff(int i, int size) {
    return i >= 0 && i < size;
}
inline double sqr(double x) {
    return x * x;
}

inline bool imageSizeFinite(const std::vector<double>& xlim, const std::vector<double>& ylim, const std::vector<double>& zlim) {
    return std::isfinite(xlim[0]) && std::isfinite(xlim[1]) &&
           std::isfinite(ylim[0]) && std::isfinite(ylim[1]) &&
           std::isfinite(zlim[0]) && std::isfinite(zlim[1]);
}

void PrintTIFF::writeTIFF(const std::string& filename, const std::vector<uint16_t>& data, uint32_t height, uint32_t width, const SimulationParameters& params) {
    
    TIFF* tiff = TIFFOpen(filename.c_str(), "w");
    if (!tiff) {
        throw std::runtime_error("Failed to open TIFF file: " + filename);
    }
    float dpi = 1.0f / params.pixelsize;

    std::string des=" Tiff file generated by BranchMorphoGen simulation.\nCopyright Sabyasachi Sutradhar, sabyasachi.sutradhar@yale.edu.\nSimulation name: " 
                    + params.SimulationName + "\nResolution: 1 pixel = " 
                    + std::to_string(params.pixelsize)+ " " + params.SpatialUnit;

    TIFFSetField(tiff, TIFFTAG_IMAGEWIDTH, width);
    TIFFSetField(tiff, TIFFTAG_IMAGELENGTH, height);
    TIFFSetField(tiff, TIFFTAG_SAMPLESPERPIXEL, 1);
    TIFFSetField(tiff, TIFFTAG_BITSPERSAMPLE, 16);
    TIFFSetField(tiff, TIFFTAG_ORIENTATION, ORIENTATION_TOPLEFT);
    TIFFSetField(tiff, TIFFTAG_PLANARCONFIG, PLANARCONFIG_CONTIG);
    TIFFSetField(tiff, TIFFTAG_PHOTOMETRIC, PHOTOMETRIC_MINISBLACK);
    TIFFSetField(tiff, TIFFTAG_XRESOLUTION, dpi);
    TIFFSetField(tiff, TIFFTAG_YRESOLUTION, dpi);
    TIFFSetField(tiff, TIFFTAG_RESOLUTIONUNIT, RESUNIT_NONE);
    TIFFSetField(tiff, TIFFTAG_IMAGEDESCRIPTION, des.c_str());
    TIFFSetField(tiff, TIFFTAG_SOFTWARE, "BranchMorphoGen");
    TIFFSetField(tiff, TIFFTAG_ARTIST, " © Sabyasachi Sutradhar, Yale University");

    for (uint32_t row = 0; row < height; ++row) {
        if (TIFFWriteScanline(tiff, const_cast<uint16_t*>(&data[row * width]), row, 0) < 0) {
            TIFFClose(tiff);
            throw std::runtime_error("Failed to write row " + std::to_string(row) + " to TIFF file.");
        }
    }
    //std::cout << "TIFF image written to " << filename << std::endl;
    TIFFClose(tiff);
}

void PrintTIFF::printImage(std::vector<Branch>& allBranches, const SimulationParameters& params, const int sample, const double& tsim) {
  double pixelsize = params.pixelsize;

uint32_t width  = 100;
uint32_t height = 100;
uint32_t padding = 0;

int ind1 = 0;
int ind2 = 1;

auto xlim = params.LimitsX.getValue(params.Time_End);
auto ylim = params.LimitsY.getValue(params.Time_End);
auto zlim = params.LimitsZ.getValue(params.Time_End);

// Choose axes for the plane
if (params.ImagePlane == "xy" || params.ImagePlane == "yx") {
    ind1 = 0; ind2 = 1;
} else if (params.ImagePlane == "xz" || params.ImagePlane == "zx") {
    ind1 = 0; ind2 = 2;
} else { // "yz" or anything else
    ind1 = 1; ind2 = 2;
}

// Compute image size and origin in world coordinates
std::array<double, 3> image_center = {0.0, 0.0, 0.0};
double origin1 = 0.0;
double origin2 = 0.0;

if (params.MAX_IMAGE_SIZE < 0 && imageSizeFinite(xlim, ylim, zlim)) {

    image_center = {
        0.5 * (xlim[0] + xlim[1]),
        0.5 * (ylim[0] + ylim[1]),
        0.5 * (zlim[0] + zlim[1])
    };

    auto extent_from_limits = [&](int axis) -> double {
        if (axis == 0) return std::fabs(xlim[1] - xlim[0]);
        if (axis == 1) return std::fabs(ylim[1] - ylim[0]);
        return std::fabs(zlim[1] - zlim[0]);
    };

    double extent1 = extent_from_limits(ind1);
    double extent2 = extent_from_limits(ind2);

    padding=static_cast<uint32_t> (ceil(params.Boundary_SoftLength/params.pixelsize));

    width  = static_cast<uint32_t>(std::ceil(extent1 / pixelsize)) + 1 + 2*padding ;//20 pixel padding
    height = static_cast<uint32_t>(std::ceil(extent2 / pixelsize)) + 1 + 2*padding ;//20 pixel padding

    // Origin corresponds to the minimum limit, not the center
    if (ind1 == 0) origin1 = xlim[0];
    if (ind1 == 1) origin1 = ylim[0];
    if (ind1 == 2) origin1 = zlim[0];

    if (ind2 == 0) origin2 = xlim[0];
    if (ind2 == 1) origin2 = ylim[0];
    if (ind2 == 2) origin2 = zlim[0];

} else {

// Number of pixels covering MAX_IMAGE_SIZE microns
   
    width  = static_cast<uint32_t>(std::ceil(params.MAX_IMAGE_SIZE / pixelsize)) + 1 ;//20 pixel padding;
    height = static_cast<uint32_t>(std::ceil(params.MAX_IMAGE_SIZE / pixelsize)) + 1 ;//20 pixel padding;

    // Image is centered on the physical root position
    image_center = {
        params.Root[0],
        params.Root[1],
        params.Root[2]
    };

    // Lower-left corner of the image in physical coordinates
    origin1 = image_center[ind1] - 0.5 * (static_cast<double>(width  - 1) * pixelsize);
    origin2 = image_center[ind2] - 0.5 * (static_cast<double>(height - 1) * pixelsize);
}
/*
    std::cout << "Printing TIFF image at time " << tsim << "s: " 
              << width << " x " << height << " pixels, "
              << pixelsize << " " << params.SpatialUnit << " per pixel." << std::endl;
*/


    // Safety
    if (width == 0)  width = 1;
    if (height == 0) height = 1;

    std::vector<double> ImRadius(width * height, 0);
    std::vector<uint16_t> ImBlurr(width * height, 0);


    static double sigma = 1.5; // Standard deviation for Gaussian kernel in pixels
    int kernel_size = static_cast<int>(std::ceil(10 * sigma));
    // make sure kernel_size is odd
        if (kernel_size % 2 == 0) {
         kernel_size += 1;
        }

    int cn =static_cast<int>(kernel_size / 2);

    std::vector<std::vector<double>> kernel(kernel_size, std::vector<double>(kernel_size, 0.0));
    double sum=0.0;
    for (int y = -cn; y <= cn; ++y) {
        for (int x = -cn; x <= cn; ++x) {
            double exponent = -(x * x + y * y) / (2.0 * sigma * sigma);
            kernel[y + cn][x + cn] = std::exp(exponent);
            sum+=kernel[y + cn][x + cn];
        }
    }

    for (int y = -cn; y <= cn; ++y) {
        for (int x = -cn; x <= cn; ++x) {
            kernel[y + cn][x + cn] = kernel[y + cn][x + cn]/sum;
        }
    }
 
    double SignalMean = params.SignalMean;
    double SignalStd  = params.SignalStd;

    for (size_t i = 0; i < allBranches.size(); ++i) {
        int pid = allBranches[i].Parent_ID;
        //int cid = allBranches[i].ID;
        Vec3 base_pt = allBranches[i].BasePoint;
        double parent_radius = (pid>=0)? allBranches[pid].Radius : params.BranchInterval ;
        //int rp=static_cast<int>(std::ceil(parent_radius / pixelsize));

        double curr_radius=allBranches[i].Radius;
        size_t jstart=(allBranches[i].Initial)? 0:1;
        for (size_t j = jstart; j < allBranches[i].Points.size(); ++j) {//ignore parent, it is already included
           
            Vec3 curr = allBranches[i].Points[j];


            Vec3 prev =  (j==0)? base_pt:allBranches[i].Points[j - 1];
            double dis = (curr - prev).norm();          
    
            if (dis <=0.0 ) continue;

            int npix = static_cast<int>(std::ceil(dis / pixelsize));
            if (npix < 1) npix = 1;

            for (int ll = 1; ll <= npix; ++ll) {
                
                double t = static_cast<double>(ll) / static_cast<double>(npix);
                Vec3 p = prev + (curr - prev)* t;
                ////ignore if within parent radius
                double base_dis= (base_pt - p).norm();
                if(base_dis<parent_radius) continue;

                int indi = padding + static_cast<int>(std::round((p[ind1] - origin1) / pixelsize));
                int indj = padding + static_cast<int>(std::round((p[ind2] - origin2) / pixelsize));

                if (Within_ImageTiff(indi, static_cast<int>(width)) &&
                    Within_ImageTiff(indj, static_cast<int>(height))) {

                int rr = static_cast<int>(std::ceil(curr_radius / pixelsize));
                if (rr < 1) rr = 1;
                

                for (int ri = indi - rr; ri <= indi + rr; ++ri) {
                    for (int rj = indj - rr; rj <= indj + rr; ++rj) {
                        double dis_center=std::sqrt((ri - indi) * (ri - indi) + (rj - indj) * (rj - indj));
                        if (Within_ImageTiff(ri, static_cast<int>(width)) &&
                            Within_ImageTiff(rj, static_cast<int>(height)) &&
                                dis_center <= rr ) {                                  
                               //double rsq = curr_radius - dis_center*pixelsize;
                               double rsq = allBranches[i].Radius;
                                double v1 = RandomUtils::Poisson(rsq * SignalMean);
                                double v2 = RandomUtils::Normal(v1, rsq * SignalStd);

                                ImRadius[static_cast<size_t>(rj) * width + static_cast<size_t>(ri)] += v2;
                            }
                        }
                    }
                }
            }

        }
    }

    for (uint32_t y = 0; y < height; ++y) {
        for (uint32_t x = 0; x < width; ++x) {
                      
        double local_sum = 0.0;
        
            for (int ky = -cn; ky <= cn; ++ky) {
                for (int kx = -cn; kx <= cn; ++kx) {
                    int iy = y + ky;
                    int ix = x + kx;
                    if (iy >= 0 && iy < static_cast<int>(height) && ix >= 0 && ix < static_cast<int>(width)) {
                        local_sum += ImRadius[iy * width + ix] * kernel[ky + cn][kx + cn];
                    }
                }
            }
                      
            local_sum += 100.0 + RandomUtils::Normal(params.BackgroundMean, params.BackgroundStd);
            ImBlurr[y * width + x] = static_cast<uint16_t>(local_sum);
        
        }
    }

        
            // Flip image vertically for non-xy planes
            for (uint32_t x = 0; x < width; ++x) {
            for (uint32_t y = 0; y < height / 2; ++y) {
                std::swap(ImBlurr[y * width + x], ImBlurr[(height - 1 - y) * width + x]);
            }
        }
        

    std::ostringstream oss;
    oss << "Conf-" << sample << "-time-" << tsim;
    std::string filename = params.SimulationName + "-" + oss.str() + ".tif";

    writeTIFF(filename, ImBlurr, height, width, params);
}

